### ISSUE TITLE
Change Design

### ISSUE THREAD

**Issue by Grezor** [Grezor/Weather-App#5]
I would like something very design, very easy to use and visualize for the user.
using a css framework or classical css.

it is possible to add icons

my design (tailwindcss)

![meteo1days](https://user-images.githubusercontent.com/38507456/107826504-49226180-6d85-11eb-8f01-dbff41278157.PNG)

### exemple idea to design
![exemple 1](https://user-images.githubusercontent.com/38507456/107826445-3445ce00-6d85-11eb-9a2f-c36947b7f9ec.png)
![weather 2](https://user-images.githubusercontent.com/38507456/107826446-360f9180-6d85-11eb-8fda-86cbc02ed5b6.jpg)

**Comment by Doringl** [comment]
https://codeburst.io/adding-city-images-to-your-react-app-14c937df2db2 you can use PlacesAPI from google, i can help you but you need to check that link well and i cant get api key for you.

**Comment by Grezor** [comment]
https://github.com/Grezor/Weather-App/discussions/8

**Comment by Grezor** [comment]
My project is in javascript, NodeJS.
Is Google Places API, is it paying ?
Are there other APIs, allowing to display the image of the city ?

**Comment by Doringl** [comment]
You can use free plan on google i think but i dont know the details.
